# vLLM Router Release Pipeline
# This pipeline is triggered on version tags (v*) to build and publish releases

env:
  CARGO_INCREMENTAL: "0"
  RUST_BACKTRACE: "1"

steps:
  # ============================================================================
  # Version Consistency Check
  # ============================================================================
  - label: ":mag: Verify Version Tag Matches pyproject.toml"
    key: "version-check"
    command: |
      set -euo pipefail

      # Extract version from git tag (e.g., v0.1.0 -> 0.1.0)
      TAG_VERSION="$${BUILDKITE_TAG#v}"
      echo "Git tag version: $TAG_VERSION"

      # Extract version from pyproject.toml
      PYPROJECT_VERSION=$(grep -E '^version\s*=' pyproject.toml | sed 's/.*=\s*"\(.*\)"/\1/')
      echo "pyproject.toml version: $PYPROJECT_VERSION"

      # Compare versions
      if [ "$TAG_VERSION" != "$PYPROJECT_VERSION" ]; then
        echo "❌ ERROR: Version mismatch!"
        echo "   Git tag version:       $TAG_VERSION"
        echo "   pyproject.toml version: $PYPROJECT_VERSION"
        echo ""
        echo "Please update pyproject.toml to match the git tag before releasing."
        exit 1
      fi

      echo "✅ Version check passed: $TAG_VERSION"
    if: build.tag =~ /^v.*/
    agents:
      queue: "cpu_queue_postmerge"

  - wait

  # ============================================================================
  # Build Release Artifacts (x86_64 and aarch64 in parallel)
  # ============================================================================
  - label: ":package: Build Release Artifacts (x86_64)"
    key: "build_wheels_x86_64"
    plugins:
      - docker#v5.11.0:
          image: "quay.io/pypa/manylinux_2_28_x86_64"
          workdir: /workdir
          volumes:
            - ".:/workdir"
          environment:
            - "CARGO_INCREMENTAL=0"
            - "RUST_BACKTRACE=1"
          command:
            - bash
            - -c
            - |
              set -euo pipefail

              # Install system dependencies (manylinux_2_28 uses dnf)
              dnf install -y openssl-devel protobuf-compiler protobuf-devel

              # Install Rust toolchain
              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly
              source $$HOME/.cargo/env

              # Build Rust binary for release
              cargo build --release

              # Build Python wheels using Python 3.9 (available in manylinux image)
              /opt/python/cp39-cp39/bin/pip install -U pip setuptools wheel setuptools-rust build auditwheel
              /opt/python/cp39-cp39/bin/python -m build

              # Repair wheel to have proper manylinux tags
              /opt/python/cp39-cp39/bin/auditwheel repair dist/*.whl -w dist/
              # Remove the original non-manylinux wheel
              rm dist/*-linux_x86_64.whl || true
    artifact_paths:
      - "target/release/vllm-router"
      - "dist/*.whl"
      - "dist/*.tar.gz"
    depends_on: "version-check"
    agents:
      queue: "cpu_queue_postmerge"

  - label: ":package: Build Release Artifacts (aarch64)"
    key: "build_wheels_aarch64"
    plugins:
      - docker#v5.11.0:
          image: "quay.io/pypa/manylinux_2_28_aarch64"
          workdir: /workdir
          volumes:
            - ".:/workdir"
          environment:
            - "CARGO_INCREMENTAL=0"
            - "RUST_BACKTRACE=1"
          command:
            - bash
            - -c
            - |
              set -euo pipefail

              # Install system dependencies (manylinux_2_28 uses dnf)
              dnf install -y openssl-devel protobuf-compiler protobuf-devel

              # Install Rust toolchain
              curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly
              source $$HOME/.cargo/env

              # Build Rust binary for release
              cargo build --release

              # Build Python wheels using Python 3.9 (available in manylinux image)
              /opt/python/cp39-cp39/bin/pip install -U pip setuptools wheel setuptools-rust build auditwheel
              /opt/python/cp39-cp39/bin/python -m build

              # Repair wheel to have proper manylinux tags
              /opt/python/cp39-cp39/bin/auditwheel repair dist/*.whl -w dist/
              # Remove the original non-manylinux wheel
              rm dist/*-linux_aarch64.whl || true
    artifact_paths:
      - "dist/*.whl"
    depends_on: "version-check"
    agents:
      queue: "arm-cpu"

  - wait

  # ============================================================================
  # Run Release Tests
  # ============================================================================
  - label: ":test_tube: Smoke Test Release Binary (x86_64)"
    key: "smoke-test-binary-x86_64"
    command: |
      buildkite-agent artifact download "target/release/vllm-router" .
      chmod +x target/release/vllm-router
      docker run --rm -v "$$PWD:/workdir" -w /workdir rustlang/rust:nightly-bullseye ./target/release/vllm-router --version
      docker run --rm -v "$$PWD:/workdir" -w /workdir rustlang/rust:nightly-bullseye ./target/release/vllm-router --help
    agents:
      queue: "cpu_queue_postmerge"

  - label: ":python: Test Python Wheel (x86_64)"
    key: "test-python-wheel-x86_64"
    command: |
      buildkite-agent artifact download "dist/*x86_64*.whl" .
      pip install dist/*x86_64*.whl
      python -c "import vllm_router; print(vllm_router.__version__)"
    agents:
      queue: "cpu_queue_postmerge"

  - label: ":python: Test Python Wheel (aarch64)"
    key: "test-python-wheel-aarch64"
    command: |
      buildkite-agent artifact download "dist/*aarch64*.whl" .
      pip install dist/*aarch64*.whl
      python -c "import vllm_router; print(vllm_router.__version__)"
    agents:
      queue: "arm-cpu"

  - wait

  # ============================================================================
  # Publish to PyPI
  # ============================================================================
  - label: ":python: Publish to PyPI"
    key: "publish-pypi"
    command: |
      set -euo pipefail

      # Download build artifacts from both architectures
      buildkite-agent artifact download "dist/*.whl" .
      buildkite-agent artifact download "dist/*.tar.gz" .

      # Upload to PyPI using Docker
      docker run --rm \
        -v "$$PWD:/workdir" \
        -w /workdir \
        -e TWINE_USERNAME=__token__ \
        -e TWINE_PASSWORD="$$PYPI_TOKEN" \
        python:3.11-slim bash -c '
          pip install twine
          echo "📦 Uploading packages to PyPI..."
          twine upload dist/* --verbose
          echo "✅ Successfully published to PyPI!"
        '
    depends_on:
      - "build_wheels_x86_64"
      - "build_wheels_aarch64"
      - "test-python-wheel-x86_64"
      - "test-python-wheel-aarch64"
      - "smoke-test-binary-x86_64"
    if: build.tag =~ /^v.*/
    soft_fail: false
    agents:
      queue: "cpu_queue_postmerge"
